// Globals
export const GET_GLOBALS = 'GET_GLOBALS';
export const GET_GLOBALS_SUCCESS = 'GET_GLOBALS_SUCCESS';
export const GET_GLOBALS_FAILED = 'GET_GLOBALS_FAILED';

// Testimonials
export const GET_TESTIMONIALS = 'GET_TESTIMONIALS';
export const GET_TESTIMONIALS_SUCCESS = 'GET_TESTIMONIALS_SUCCESS';
export const GET_TESTIMONIALS_FAILED = 'GET_TESTIMONIALS_FAILED';

// Configurator
export const GET_CONFIGURATOR = 'GET_CONFIGURATOR';
export const GET_CONFIGURATOR_SUCCESS = 'GET_CONFIGURATOR_SUCCESS';
export const GET_CONFIGURATOR_FAILED = 'GET_CONFIGURATOR_FAILED';
